---
start:
  datefmt: Y-m-d
  date: yesterday
end:
  datefmt: Y-m-d
  date: yesterday
mapConfig:
  zoom: 2
  center:
    lat: 0.0
    lng: 0.0

# minPins: How many pins to leave on the map when pulling up pins.
minPins: 30

# Fetching new pins (and content request counts) in ms.
fetchPinInterval: 60000
# Only fetch pins if we have fewer than this many.
fetchPinLevel: 180

# How often to drop one or more pins.
dropPinInterval: 1000

# How often to pick up one pin.
pullPinInterval: 1000

# This appears in the info bubble when a pin is clicked.
infoTemplate: >-
  <article>
    <h2 class="m-type-size-S">Reader from $pin.location</h2>
    <p>
      <img class="access $pin.access" src="assets/images/$pin.access.svg" alt="$pin.access access">
      <span class="metadata">
        <span class="title"><a href="$pin.url" target="_blank">$pin.title</a></span>
        <span class="author">$pin.author</span>
      </span>
    </p>
  </article>

# The probibility density for dropping more than one pin at a time.
pinDistribution:
  - weight: 0.70
    count: 1
  - weight: 0.20
    count: 2
  - weight: 0.10
    count: 3

# The list of views to gather pageviews and events from.
accounts:
  #MPub quod.lib colls, part 1
  - id: 10966839
    metrics: ga:pageviews
    filters: ga:pagePath=~(seq=|view=text|view=fulltext|view=pdf)
  - id: 10966839
    metrics: ga:totalEvents
    filters: ga:eventAction=~Item View
  - id: 10966839
    metrics: ga:totalEvents
    filters: ga:eventCategory=~PDF Download
  #MPub quod.lib colls, part 2
  - id: 35132797
    metrics: ga:pageviews
    filters: ga:pagePath=~(seq=|view=text|view=fulltext|view=pdf)
  - id: 35132797
    metrics: ga:totalEvents
    filters: ga:eventAction=~Item View
  - id: 35132797
    metrics: ga:totalEvents
    filters: ga:eventCategory=~PDF Download
views:
  #Fulcrum (all)
  - id: 133129661
    metrics: ga:pageviews
    filters: ga:pagePath=~^/(concern/.+?|epubs)/([A-Za-z0-9])
  - id: 133129661
    metrics: ga:totalEvents
    filters: ga:eventAction=~download_
  #Fulcrum / Michigan
  - id: 132442623
    metrics: ga:pageviews
    filters: ga:pagePath=~^/(concern/.+?|epubs)/([A-Za-z0-9])
  - id: 132442623
    metrics: ga:totalEvents
    filters: ga:eventAction=~download_
  #Fulcrum / HEB
  - id: 22140843
    metrics: ga:pageviews
    filters: ga:pagePath=~^/(concern/.+?|epubs)/([A-Za-z0-9])
  - id: 22140843
    metrics: ga:totalEvents
    filters: ga:eventAction=~download_
  # Fulcrum / Lever Press
  - id: 123826825
    metrics: ga:pageviews
    filters: ga:pagePath=~^/(concern/.+?|epubs)/([A-Za-z0-9])
    start:
      datefmt: Y-m-d
      date: -4 weeks
    end:
      datefmt: Y-m-d
      date: yesterday
  - id: 123826825
    metrics: ga:totalEvents
    filters: ga:eventAction=~download_
    start:
      datefmt: Y-m-d
      date: -4 weeks
    end:
      datefmt: Y-m-d
      date: yesterday
  # Fulcrum / Amherst College Press
  - id: 202426456
    metrics: ga:pageviews
    filters: ga:pagePath=~^/(concern/.+?|epubs)/([A-Za-z0-9])
    start:
      datefmt: Y-m-d
      date: -4 weeks
    end:
      datefmt: Y-m-d
      date: yesterday
  - id: 202426456
    metrics: ga:totalEvents
    filters: ga:eventAction=~download_
    start:
      datefmt: Y-m-d
      date: -4 weeks
    end:
      datefmt: Y-m-d
      date: yesterday
  # Fulcrum / UMMAA
  - id: 218624776
    metrics: ga:pageviews
    filters: ga:pagePath=~^/(concern/.+?|epubs)/([A-Za-z0-9])
    start:
      datefmt: Y-m-d
      date: -4 weeks
    end:
      datefmt: Y-m-d
      date: yesterday
  - id: 218624776
    metrics: ga:totalEvents
    filters: ga:eventAction=~download_
    start:
      datefmt: Y-m-d
      date: -4 weeks
    end:
      datefmt: Y-m-d
      date: yesterday
  # Deep Blue Data
  - id: 120812821
    metrics: ga:totalEvents
    filters: ga:eventAction=~downloaded
  - id: 120812821
    metrics: ga:pageviews
    filters: ga:pagePath=~data/downloads
  # Deep Blue Docs
  - id: 150701143
    metrics: ga:pageviews
    filters: ga:pagePath=~bitstream
  - id: 150701143
    metrics: ga:totalEvents
    filters: ga:eventCategory=~Download
  #Fulcrum / UM Center for Chinese Studies (UMCCS)
  - id: 218616260
    metrics: ga:pageviews
    filters: ga:pagePath=~^/(concern/.+?|epubs)/([A-Za-z0-9])
  - id: 218616260
    metrics: ga:totalEvents
    filters: ga:eventAction=~download_
  #Fulcrum / UM Center for Japanese Studies (UMCJS)
  - id: 218667833
    metrics: ga:pageviews
    filters: ga:pagePath=~^/(concern/.+?|epubs)/([A-Za-z0-9])
  - id: 218667833
    metrics: ga:totalEvents
    filters: ga:eventAction=~download_
  #Fulcrum / UM Center for Southeast Asian Studies (UMCSEAS)
  - id: 219834111
    metrics: ga:pageviews
    filters: ga:pagePath=~^/(concern/.+?|epubs)/([A-Za-z0-9])
  - id: 219834111
    metrics: ga:totalEvents
    filters: ga:eventAction=~download_
  #Fulcrum / UM Center for South Asian Studies (UMCSAS)
  - id: 219840920
    metrics: ga:pageviews
    filters: ga:pagePath=~^/(concern/.+?|epubs)/([A-Za-z0-9])
  - id: 219840920
    metrics: ga:totalEvents
    filters: ga:eventAction=~download_
